### PR TITLE
Tatar ModMenu Description Translation.

### PR DESCRIPTION
**Pull request by Amirhan-Taipovjan-Greatest-I**

### CODE REVIEW

**Comment by henkelmax** [comment]
This mod doesn't have any translations and doesn't include ModMenu integration.

**Comment by Amirhan-Taipovjan-Greatest-I** [comment]
Ok.

**Comment by henkelmax** [comment]
No clue what you mean.

**Comment by Amirhan-Taipovjan-Greatest-I** [comment]
> No clue what you mean.

I mean that this mod has own description that appears in ModMenu, and I translated it.

**Comment by henkelmax** [comment]
This is the mod description thats part of fabric. This has nothing to do with modmenu. Modmenu just reads this field.

**Pull request closed without merging**
